# Generated by Django 3.0.5 on 2020-06-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_charge_chargemanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChargeManager',
        ),
        migrations.AddField(
            model_name='card',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
