# Generated by Django 3.0.5 on 2020-05-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usersession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='csession_key',
        ),
        migrations.AddField(
            model_name='usersession',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
