# Generated by Django 3.0.5 on 2020-06-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingpreferece',
            name='mailchimp_subscribed',
            field=models.NullBooleanField(),
        ),
    ]
