# Generated by Django 3.0.5 on 2020-08-07 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_marketingpreferece_mailchimp_subscribed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarketingPreferece',
        ),
    ]
